mongo_uri: mongodb://localhost/convai

facebook:
  page_access_token: "ddd"
  webhook_secret: "https://45.12.74.38:8443"
  webhook: "fdfddd"
  token: "301781569:AAGbcG5X3CScuewPbWzoIZ8bgkzXsJyFBzw"

telegram:
  webhook: "https://45.12.74.38:8443"
  token: "875920449:AAGU7QZLlTE5oC8uPlO3k8DCAu27DN4oiII"

dialog_options:
  max_time_in_lobby: 300
  human_bot_ratio: 1.0
  inactivity_timeout: 300
  max_length: 1000
  n_bad_messages_in_a_row_threshold: 10
  assign_profile: false
  show_topics: true
  n_messages_to_switch_topic: 20
  allow_set_bot: false
  reveal_dialog_id: true
  use_images: false

evaluation_options:
  score_dialog: false
  evaluation_score_from: 1
  evaluation_score_to: 5
  evaluate_message_required: false
  guess_profile: false
  guess_profile_sentence_by_sentence: false

logging:
  root_path: ~/log/convai-router
  base_level: DEBUG
